###

POST  http://localhost:9000/
Content-Type: application/json

{
    "mis" : 1119160,
    "password" : "yaswanth"
}

###

POST http://localhost:9000/signup/
Content-Type: application/json

{
    "mis" : 1119160,
    "password" : "yaswanth",
    "email" : "yas@gmail.com"
}

###

GET http://localhost:9000/books
Content-Type: application/json

{
    "searchInput" : "za"
}